spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        search:
          default:
            directory__provider: filesystem
            indexBase: indexpath
            indexwriter:
              infostream: true

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/avito-db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  cache:
    ehcache:
      config: classpath:ehcache.xml